resources:
  repositories:
    - repository: pipelineTemplate
      type: github
      name: lenn-hnkl/pipeline-template
      ref: refs/tags/2.7.0

extends:
  template: template.yml@pipelineTemplate